version: '2'
services:
    eoffice-app:
        image: eoffice
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=eoffice-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    eoffice-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: eoffice-cassandra
    eoffice-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=eoffice-cassandra
    eoffice-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: eoffice-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
